name-template: '{{default "Release" release}}'
tag-template: '{{version}}'
categories:
  - name: 'Features'
    label: 'feature'
    match:
      - type: 'pull_request'
        label: 'feature'
  - name: 'Bug Fixes'
    label: 'bug'
    match:
      - type: 'pull_request'
        label: 'bug'
  - name: 'Documentation'
    label: 'documentation'
    match:
      - type: 'pull_request'
        label: 'documentation'
  - name: 'Other Changes'
    label: ''
    match:
      - type: 'pull_request'
  - name: 'Known Issues'
    label: 'known issue'
    match:
      - type: 'issue'
        label: 'known issue'

template: |
  {{#if notes}}
  {{#each notes}}
  {{this}}
  {{/each}}
  {{/if}}

  {{#each categories}}
  {{#if changes.[this.name]}}
  ### {{this.name}}

  {{#each changes.[this.name]}}
  - {{#if this.pull_request}}
    [{{this.pull_request.title}}]({{this.pull_request.html_url}}) ([#{{this.pull_request.number}}]({{this.pull_request.html_url}}))
    {{/if}}
    {{#if this.issue}}
    [{{this.issue.title}}]({{this.issue.html_url}}) ([#{{this.issue.number}}]({{this.issue.html_url}}))
    {{/if}}
    {{#if this.labels}}
    {{#each this.labels}}
    {{this}} 
    {{/each}}
    {{/if}}
  {{/each}}

  {{/if}}
  {{/each}}
